# Generated by Django 4.2.1 on 2023-05-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dec',
            field=models.TextField(default='Default description'),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=1900),
        ),
    ]
