# Generated by Django 4.2.1 on 2023-05-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_dec_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='dec',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(),
        ),
    ]
