# Generated by Django 4.2.1 on 2023-05-26 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_alter_movie_dec_alter_movie_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='dec',
            new_name='desc',
        ),
    ]
